# Generated by Django 5.0.3 on 2024-03-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_product_created_at_product_discount_product_flout'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arvay',
            field=models.BooleanField(default=False),
        ),
    ]
