# Generated by Django 5.0.3 on 2024-03-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_product_arvay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='flout',
            new_name='prise',
        ),
    ]
