# Generated by Django 5.1.1 on 2024-09-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-prise', 'name')},
        ),
    ]
